#include <bits/stdc++.h>
using namespace std; using U=uint64_t;
struct Case{int B,E,sp;string core;vector<pair<int,int>>ed;};
static vector<string> split(const string&s,char sep){vector<string>v;string x;stringstream ss(s);while(getline(ss,x,sep))v.push_back(x);return v;}
static bool exact_path(const vector<U>&a,int s,int t,int L){struct S{int v,d;U used;};vector<S>st;st.reserve(512);st.push_back({s,0,1ULL<<s});while(!st.empty()){auto q=st.back();st.pop_back();if(q.d==L){if(q.v==t)return true;continue;}U c=a[q.v]&~q.used;if(q.d<L-1)c&=~(1ULL<<t);while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);st.push_back({w,q.d+1,q.used|b});}}return false;}
static bool badedge(const vector<U>&a,int u,int v){return exact_path(a,u,v,3)||exact_path(a,u,v,7)||exact_path(a,u,v,15);}
static bool two_deg(vector<U>a){int n=a.size();U alive=(1ULL<<n)-1;vector<int>d(n);for(int i=0;i<n;i++)d[i]=__builtin_popcountll(a[i]);for(int k=0;k<n;k++){int v=-1;for(int i=0;i<n;i++)if((alive>>i&1)&&d[i]<=2){v=i;break;}if(v<0)return false;alive&=~(1ULL<<v);U c=a[v]&alive;while(c){U b=c&-c;c-=b;d[__builtin_ctzll(b)]--;}}return true;}
static vector<Case> readcases(string path){ifstream in(path);string l;getline(in,l);if(l!="ENDPOINT_CASES_V1")throw runtime_error("case header");vector<Case>out;while(getline(in,l)){if(l=="END")break;if(l.empty())continue;istringstream s(l);string tag;Case c;s>>tag>>c.B>>c.E>>c.core>>c.sp;if(tag!="CASE")throw runtime_error("CASE");getline(in,l);istringstream es(l);es>>tag;if(tag!="EDGES")throw runtime_error("EDGES");string x;while(es>>x){auto p=x.find(',');c.ed.push_back({stoi(x.substr(0,p)),stoi(x.substr(p+1))});}getline(in,l);if(l!="ENDCASE")throw runtime_error("ENDCASE");out.push_back(move(c));}return out;}
static string key(int B,int E,string core,int sp){return to_string(B)+"|"+to_string(E)+"|"+core+"|"+to_string(sp);}
static map<string,vector<int>> readbudget(string path){ifstream in(path);string l;getline(in,l);map<string,vector<int>>M;while(getline(in,l)){if(l.empty())continue;auto f=split(l,',');if(f.size()!=6)throw runtime_error("budget csv fields");int B=stoi(f[0]),E=stoi(f[1]),sp=stoi(f[3]),sum=stoi(f[4]);string w=f[5];if(!w.empty()&&w.front()=='\"')w.erase(w.begin());if(!w.empty()&&w.back()=='\"')w.pop_back();istringstream ss(w);vector<int>v;int x;while(ss>>x)v.push_back(x);if(accumulate(v.begin(),v.end(),0)!=sum)throw runtime_error("budget sum field");M[key(B,E,f[2],sp)]=move(v);}return M;}
struct Stats{long long states=0,attempts=0,closures=0;};
static bool verify_case(const Case&C,const vector<int>&lam,Stats&S,string &why){int B=C.B,EP=C.ed.size(),y=C.E?17:16,base=B+EP;if((int)lam.size()!=EP){why="lambda length";return false;}for(int x:lam)if(x<0||x>2){why="lambda outside 0..2";return false;}if(accumulate(lam.begin(),lam.end(),0)>=y){why="lambda sum not < y";return false;}if(EP!=2*B-8){why="edge count";return false;}
 vector<int>deg(B);set<pair<int,int>>seen;vector<U>q(B);for(auto [u0,v0]:C.ed){int u=u0,v=v0;if(u==v||u<0||v<0||u>=B||v>=B){why="bad edge";return false;}if(u>v)swap(u,v);if(!seen.insert({u,v}).second){why="parallel";return false;}deg[u]++;deg[v]++;q[u]|=1ULL<<v;q[v]|=1ULL<<u;}if(!two_deg(q)){why="not 2deg";return false;}for(auto[u,v]:seen)if(exact_path(q,u,v,3)||exact_path(q,u,v,7)){why="Q C4/C8";return false;}
 vector<int>cap(B);for(int v=0;v<B;v++){cap[v]=4+((C.E&&v==C.sp)?1:0)-deg[v];if(cap[v]<0){why="neg cap";return false;}}if(accumulate(cap.begin(),cap.end(),0)!=y){why="cap sum";return false;}
 vector<U>g(base+y);auto add=[&](int u,int v){g[u]|=1ULL<<v;g[v]|=1ULL<<u;};auto del=[&](int u,int v){g[u]&=~(1ULL<<v);g[v]&=~(1ULL<<u);};for(int e=0;e<EP;e++){add(B+e,C.ed[e].first);add(B+e,C.ed[e].second);}for(int u=0;u<base;u++){U c=g[u]&~((1ULL<<(u+1))-1);while(c){U b=c&-c;c-=b;int v=__builtin_ctzll(b);if(badedge(g,u,v)){why="base forbidden";return false;}}}
 vector<int>rem=cap,seq;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){int lim=lam[i]+lam[j],st=B+i,tg=B+j;function<bool(int)>rec=[&](int dep){S.states++;if(dep>=y)return true;int prev=dep?base+dep-1:st,node=base+dep;for(int lab=0;lab<B;lab++)if(rem[lab]){S.attempts++;add(node,lab);add(prev,node);rem[lab]--;seq.push_back(lab);if(!badedge(g,prev,node)){add(node,tg);S.closures++;bool safe=!badedge(g,node,tg);del(node,tg);if(safe&&dep+1>lim){why="violating path endpoints="+to_string(i)+","+to_string(j)+" k="+to_string(dep+1)+" word=";for(int x:seq)why+=to_string(x)+" ";seq.pop_back();rem[lab]++;del(prev,node);del(node,lab);return false;}if(!rec(dep+1)){seq.pop_back();rem[lab]++;del(prev,node);del(node,lab);return false;}}seq.pop_back();rem[lab]++;del(prev,node);del(node,lab);}return true;};if(!rec(0))return false;}return true;}
int main(int argc,char**argv){if(argc!=3){cerr<<"usage cases budget.csv\n";return 2;}auto cs=readcases(argv[1]);auto M=readbudget(argv[2]);Stats S;map<pair<int,int>,int>cnt,maxsum;for(auto&C:cs){auto it=M.find(key(C.B,C.E,C.core,C.sp));if(it==M.end()){cerr<<"missing budget "<<C.core<<"\n";return 3;}string why;if(!verify_case(C,it->second,S,why)){cerr<<"FAIL "<<C.B<<","<<C.E<<" "<<C.core<<" sp="<<C.sp<<" "<<why<<"\n";return 10;}cnt[{C.B,C.E}]++;maxsum[{C.B,C.E}]=max(maxsum[{C.B,C.E}],accumulate(it->second.begin(),it->second.end(),0));}cout<<"PASS CASES "<<cs.size()<<" STATES "<<S.states<<" ATTEMPTS "<<S.attempts<<" CLOSURES "<<S.closures<<"\n";for(auto[k,n]:cnt)cout<<"SECTOR "<<k.first<<","<<k.second<<" CASES "<<n<<" MAX_BUDGET "<<maxsum[k]<<" y="<<(k.second?17:16)<<"\n";}
