#include <bits/stdc++.h>
using namespace std; using U=uint64_t;
struct Case{int B,E,sp,idx;string core;vector<pair<int,int>>ed;};
struct POpt{int i,j;vector<uint8_t>w;array<uint8_t,8>cnt{};};
struct TOpt{array<int,3> ep{};array<vector<uint8_t>,3> arms;array<uint8_t,8>cnt{};};
struct LOpt{int ep;vector<uint8_t>tail,cyc;array<uint8_t,8>cnt{};};
struct COpt{vector<uint8_t>w;array<uint8_t,8>cnt{};};
static void add(vector<U>&a,int u,int v){a[u]|=1ULL<<v;a[v]|=1ULL<<u;} static void del(vector<U>&a,int u,int v){a[u]&=~(1ULL<<v);a[v]&=~(1ULL<<u);}
static bool cdfs_direct(const vector<U>&a,int s,int v,int L,int dep,U used){if(dep==L-1)return (a[v]>>s)&1ULL;U c=a[v]&~used;while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);if(cdfs_direct(a,s,w,L,dep+1,used|b))return true;}return false;}
static bool cycle_through_direct(const vector<U>&a,int s,int L){U c=a[s];while(c){U b=c&-c;c-=b;int f=__builtin_ctzll(b);if(cdfs_direct(a,s,f,L,1,(1ULL<<s)|b))return true;}return false;}
static bool safe_add(vector<U>&g,int u,int v,long long&checks){checks++;add(g,u,v);if(cycle_through_direct(g,u,4)||cycle_through_direct(g,u,8)||cycle_through_direct(g,u,16)){del(g,u,v);return false;}return true;}
static vector<Case>readcases(const string&p){ifstream in(p);string l;getline(in,l);vector<Case>o;int idx=0;while(getline(in,l)){if(l=="END")break;if(l.empty())continue;istringstream ss(l);string t;Case c;ss>>t>>c.B>>c.E>>c.core>>c.sp;getline(in,l);istringstream es(l);es>>t;string x;while(es>>x){auto z=x.find(',');c.ed.push_back({stoi(x.substr(0,z)),stoi(x.substr(z+1))});}getline(in,l);c.idx=idx++;o.push_back(c);}return o;}
static vector<int> canon_cycle(const vector<uint8_t>&w){int m=w.size();vector<int>best;for(auto x:w)best.push_back(x);for(int rev=0;rev<2;rev++){vector<uint8_t>q=w;if(rev)reverse(q.begin(),q.end());for(int r=0;r<m;r++){vector<int>z;for(int k=0;k<m;k++)z.push_back(q[(r+k)%m]);if(z<best)best=z;}}return best;}
struct Search{
 Case C;int B,EP,d,y,base,Z,nmax;vector<int>cap;vector<U>baseg,g;vector<vector<vector<POpt>>>P;vector<TOpt>T;vector<LOpt>L;vector<COpt>Cyc;long long localChecks=0,globalChecks=0,localNodes=0,globalStates=0;vector<POpt>solP;optional<TOpt>solT;optional<LOpt>solL;
 Search(Case cc):C(cc){B=C.B;EP=C.ed.size();d=2*B-EP;y=2*d+C.E;base=B+EP;Z=base+y;nmax=Z+1;vector<int>deg(B);for(auto [u,v]:C.ed)deg[u]++,deg[v]++;cap.resize(B);for(int v=0;v<B;v++)cap[v]=4+((C.E&&v==C.sp)?1:0)-deg[v];baseg.assign(nmax,0);for(int e=0;e<EP;e++){add(baseg,B+e,C.ed[e].first);add(baseg,B+e,C.ed[e].second);}g=baseg;P.resize(EP,vector<vector<POpt>>(EP));}
 bool fits(const array<uint8_t,8>&c,const array<int,8>&rem){for(int v=0;v<B;v++)if(c[v]>rem[v])return false;return true;}
 void genPaths(){vector<int>rem=cap;vector<uint8_t>w;array<uint8_t,8>cnt{};for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){auto h0=baseg;if(safe_add(h0,B+i,B+j,localChecks)){POpt o;o.i=i;o.j=j;P[i][j].push_back(o);}function<void(int,vector<U>&)>rec=[&](int dep,vector<U>&h){localNodes++;if(dep>=y)return;int prev=dep?base+dep-1:B+i,node=base+dep;for(int lab=0;lab<B;lab++)if(rem[lab]){vector<pair<int,int>>ad;add(h,node,lab);ad.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=safe_add(h,prev,node,localChecks);if(ok)ad.push_back({prev,node});if(ok){if(safe_add(h,node,B+j,localChecks)){POpt o;o.i=i;o.j=j;o.w=w;o.cnt=cnt;P[i][j].push_back(o);del(h,node,B+j);}rec(dep+1,h);}for(auto it=ad.rbegin();it!=ad.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};auto h=baseg;rec(0,h);}}
 void genTripods(){for(int e0=0;e0<EP;e0++)for(int e1=e0+1;e1<EP;e1++)for(int e2=e1+1;e2<EP;e2++){array<int,3>eps{e0,e1,e2};vector<int>rem=cap;array<uint8_t,8>cnt{};array<vector<uint8_t>,3>arms;auto h=baseg;function<void(int,int)> nextArm; nextArm=[&](int ai,int used){localNodes++;if(ai==3){TOpt o;o.ep=eps;o.arms=arms;o.cnt=cnt;T.push_back(o);return;}int target=B+eps[ai]; // empty arm
   if(safe_add(h,Z,target,localChecks)){arms[ai].clear();nextArm(ai+1,used);del(h,Z,target);}vector<uint8_t>w;function<void(int)> grow=[&](int len){if(used+len>=y)return;int prev=len?base+used+len-1:Z,node=base+used+len;for(int lab=0;lab<B;lab++)if(rem[lab]){vector<pair<int,int>>ad;add(h,node,lab);ad.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=safe_add(h,prev,node,localChecks);if(ok)ad.push_back({prev,node});if(ok){if(safe_add(h,node,target,localChecks)){arms[ai]=w;nextArm(ai+1,used+len+1);del(h,node,target);}grow(len+1);}for(auto it=ad.rbegin();it!=ad.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};grow(0);};nextArm(0,0);}}
 void genLollipops(){for(int ep=0;ep<EP;ep++){vector<int>rem=cap;array<uint8_t,8>cnt{};auto h=baseg;vector<uint8_t>tail;function<void(int)> cycleGen=[&](int used){vector<uint8_t>w;function<void(int)>grow=[&](int len){if(used+len>=y)return;int prev=len?base+used+len-1:Z,node=base+used+len;for(int lab=0;lab<B;lab++)if(rem[lab]){vector<pair<int,int>>ad;add(h,node,lab);ad.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=safe_add(h,prev,node,localChecks);if(ok)ad.push_back({prev,node});if(ok){if(len+1>=2&&safe_add(h,node,Z,localChecks)){vector<uint8_t>rw=w;reverse(rw.begin(),rw.end());if(w<=rw){LOpt o;o.ep=ep;o.tail=tail;o.cyc=w;o.cnt=cnt;L.push_back(o);}del(h,node,Z);}grow(len+1);}for(auto it=ad.rbegin();it!=ad.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};grow(0);};
   int target=B+ep; // empty tail
   if(safe_add(h,Z,target,localChecks)){tail.clear();cycleGen(0);del(h,Z,target);}vector<uint8_t>w;function<void(int)>growTail=[&](int len){if(len>=y)return;int prev=len?base+len-1:Z,node=base+len;for(int lab=0;lab<B;lab++)if(rem[lab]){vector<pair<int,int>>ad;add(h,node,lab);ad.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=safe_add(h,prev,node,localChecks);if(ok)ad.push_back({prev,node});if(ok){if(safe_add(h,node,target,localChecks)){tail=w;cycleGen(len+1);del(h,node,target);}growTail(len+1);}for(auto it=ad.rbegin();it!=ad.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};growTail(0);}}
 void genCycles(){vector<int>rem=cap;vector<uint8_t>w;array<uint8_t,8>cnt{};set<vector<int>>seen;for(int m=3;m<=y;m++){function<void(int,vector<U>&)>rec=[&](int pos,vector<U>&h){localNodes++;if(pos==m){if(safe_add(h,base+m-1,base,localChecks)){auto can=canon_cycle(w);if(seen.insert(can).second){COpt o;o.w=w;o.cnt=cnt;Cyc.push_back(o);}del(h,base+m-1,base);}return;}for(int lab=0;lab<B;lab++)if(rem[lab]){if(pos>0&&lab<w[0])continue;int node=base+pos;vector<pair<int,int>>ad;add(h,node,lab);ad.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=true;if(pos>0){ok=safe_add(h,base+pos-1,node,localChecks);if(ok)ad.push_back({base+pos-1,node});}if(ok)rec(pos+1,h);for(auto it=ad.rbegin();it!=ad.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};auto h=baseg;rec(0,h);} }
 bool addPath(const POpt&o,int used,vector<pair<int,int>>&ad){if(o.w.empty()){if(!safe_add(g,B+o.i,B+o.j,globalChecks))return false;ad.push_back({B+o.i,B+o.j});return true;}int prev=B+o.i;for(int k=0;k<(int)o.w.size();k++){int node=base+used+k,lab=o.w[k];add(g,node,lab);ad.push_back({node,lab});if(!safe_add(g,prev,node,globalChecks))return false;ad.push_back({prev,node});prev=node;}if(!safe_add(g,prev,B+o.j,globalChecks))return false;ad.push_back({prev,B+o.j});return true;}
 bool addTripod(const TOpt&o,vector<pair<int,int>>&ad){int used=0;for(int ai=0;ai<3;ai++){int prev=Z;for(auto lab:o.arms[ai]){int node=base+used++;add(g,node,lab);ad.push_back({node,lab});if(!safe_add(g,prev,node,globalChecks))return false;ad.push_back({prev,node});prev=node;}if(!safe_add(g,prev,B+o.ep[ai],globalChecks))return false;ad.push_back({prev,B+o.ep[ai]});}return true;}
 bool addLollipop(const LOpt&o,vector<pair<int,int>>&ad){int used=0,prev=Z;for(auto lab:o.tail){int node=base+used++;add(g,node,lab);ad.push_back({node,lab});if(!safe_add(g,prev,node,globalChecks))return false;ad.push_back({prev,node});prev=node;}if(!safe_add(g,prev,B+o.ep,globalChecks))return false;ad.push_back({prev,B+o.ep});prev=Z;int first=-1;for(auto lab:o.cyc){int node=base+used++;if(first<0)first=node;add(g,node,lab);ad.push_back({node,lab});if(!safe_add(g,prev,node,globalChecks))return false;ad.push_back({prev,node});prev=node;}if(!safe_add(g,prev,Z,globalChecks))return false;ad.push_back({prev,Z});return true;}
 bool addCycle(const COpt&o,int used,vector<pair<int,int>>&ad){int m=o.w.size();for(int k=0;k<m;k++){int node=base+used+k,lab=o.w[k];add(g,node,lab);ad.push_back({node,lab});if(k>0){if(!safe_add(g,base+used+k-1,node,globalChecks))return false;ad.push_back({base+used+k-1,node});}}if(!safe_add(g,base+used+m-1,base+used,globalChecks))return false;ad.push_back({base+used+m-1,base+used});return true;}
 bool fillCycles(array<int,8>&rem,int used){int total=0;for(int v=0;v<B;v++)total+=rem[v];if(total==0)return true;int v0=0;while(v0<B&&rem[v0]==0)v0++;for(auto&o:Cyc){if(o.cnt[v0]==0||!fits(o.cnt,rem))continue;vector<pair<int,int>>ad;if(!addCycle(o,used,ad)){for(auto it=ad.rbegin();it!=ad.rend();++it)del(g,it->first,it->second);continue;}for(int v=0;v<B;v++)rem[v]-=o.cnt[v];if(fillCycles(rem,used+o.w.size()))return true;for(int v=0;v<B;v++)rem[v]+=o.cnt[v];for(auto it=ad.rbegin();it!=ad.rend();++it)del(g,it->first,it->second);}return false;}
 void undo(vector<pair<int,int>>&ad){for(auto it=ad.rbegin();it!=ad.rend();++it)del(g,it->first,it->second);}
 bool dfsPaths(uint16_t mask,array<int,8>&rem,int used){globalStates++;if(mask==(1u<<EP)-1){return fillCycles(rem,used);}int i=0;while(mask>>i&1)i++;for(int j=i+1;j<EP;j++)if(!(mask>>j&1)){for(auto&o:P[i][j]){if(!fits(o.cnt,rem))continue;vector<pair<int,int>>ad;if(!addPath(o,used,ad)){undo(ad);continue;}for(int v=0;v<B;v++)rem[v]-=o.cnt[v];solP.push_back(o);if(dfsPaths(mask|(1u<<i)|(1u<<j),rem,used+o.w.size()))return true;solP.pop_back();for(int v=0;v<B;v++)rem[v]+=o.cnt[v];undo(ad);}}return false;}
 bool run(){genPaths();genTripods();genLollipops();genCycles();array<int,8>init{};for(int v=0;v<B;v++)init[v]=cap[v]; // special first, then paths
  for(auto&o:T){auto rem=init;if(!fits(o.cnt,rem))continue;g=baseg;vector<pair<int,int>>ad;if(!addTripod(o,ad))continue;for(int v=0;v<B;v++)rem[v]-=o.cnt[v];uint16_t mask=0;for(int e:o.ep)mask|=1u<<e;solT=o;solL.reset();solP.clear();int used=0;for(auto&a:o.arms)used+=a.size();if(dfsPaths(mask,rem,used))return true;solT.reset();}
  for(auto&o:L){auto rem=init;if(!fits(o.cnt,rem))continue;g=baseg;vector<pair<int,int>>ad;if(!addLollipop(o,ad))continue;for(int v=0;v<B;v++)rem[v]-=o.cnt[v];uint16_t mask=1u<<o.ep;solL=o;solT.reset();solP.clear();int used=o.tail.size()+o.cyc.size();if(dfsPaths(mask,rem,used))return true;solL.reset();}
  return false;}
 void report(bool yes){long long pc=0;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++)pc+=P[i][j].size();cout<<(yes?"GLOBAL_SAT":"GLOBAL_UNSAT")<<" idx="<<C.idx<<" "<<C.core<<" E="<<C.E<<" sp="<<C.sp<<" paths="<<pc<<" tripods="<<T.size()<<" lollipops="<<L.size()<<" cycles="<<Cyc.size()<<" gstates="<<globalStates<<" lchecks="<<localChecks<<" gchecks="<<globalChecks<<" lnodes="<<localNodes<<"\n";if(yes){if(solT){cout<<" TRIPOD EPS";for(int e:solT->ep)cout<<" "<<e;cout<<"\n";for(int a=0;a<3;a++){cout<<"  ARM"<<a;for(auto x:solT->arms[a])cout<<" "<<(int)x;cout<<"\n";}}if(solL){cout<<" LOLLIPOP EP "<<solL->ep<<" TAIL";for(auto x:solL->tail)cout<<" "<<(int)x;cout<<" CYC";for(auto x:solL->cyc)cout<<" "<<(int)x;cout<<"\n";}for(auto&o:solP){cout<<" PATH "<<o.i<<" "<<o.j<<" W";for(auto x:o.w)cout<<" "<<(int)x;cout<<"\n";}}}
};
int main(int argc,char**argv){auto cs=readcases(argv[1]);int lo=0,hi=cs.size();if(argc>=4){lo=stoi(argv[2]);hi=stoi(argv[3]);}for(int i=lo;i<hi;i++){Search s(cs[i]);bool yes=s.run();s.report(yes);} }
