#include <bits/stdc++.h>
using namespace std; using U=uint64_t;
struct Case{int B,E,sp,idx;string core;vector<pair<int,int>>ed;};
struct POpt{int i,j;vector<uint8_t>w;array<uint8_t,8>cnt{};};
struct COpt{vector<uint8_t>w;array<uint8_t,8>cnt{};};
static void add(vector<U>&a,int u,int v){a[u]|=1ULL<<v;a[v]|=1ULL<<u;} static void del(vector<U>&a,int u,int v){a[u]&=~(1ULL<<v);a[v]&=~(1ULL<<u);}
static bool exact_path(const vector<U>&a,int s,int t,int L){struct S{int v,d;U used;};vector<S>st{{s,0,1ULL<<s}};while(!st.empty()){auto q=st.back();st.pop_back();if(q.d==L){if(q.v==t)return true;continue;}U c=a[q.v]&~q.used;if(q.d<L-1)c&=~(1ULL<<t);while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);st.push_back({w,q.d+1,q.used|b});}}return false;}
static bool safe_add(vector<U>&g,int u,int v,long long &checks){checks++;if(exact_path(g,u,v,3)||exact_path(g,u,v,7)||exact_path(g,u,v,15))return false;add(g,u,v);return true;}
static vector<Case> readcases(const string&p){ifstream in(p);string l;if(!getline(in,l))throw runtime_error("header");vector<Case>o;int idx=0;while(getline(in,l)){if(l=="END")break;if(l.empty())continue;istringstream ss(l);string t;Case c;ss>>t>>c.B>>c.E>>c.core>>c.sp;getline(in,l);istringstream es(l);es>>t;string x;while(es>>x){auto z=x.find(',');c.ed.push_back({stoi(x.substr(0,z)),stoi(x.substr(z+1))});}getline(in,l);c.idx=idx++;o.push_back(c);}return o;}
static vector<int> canon_cycle(const vector<uint8_t>&w){int m=w.size();vector<int>best;for(int i=0;i<m;i++)best.push_back(w[i]);for(int rev=0;rev<2;rev++){vector<uint8_t>q=w;if(rev)reverse(q.begin(),q.end());for(int r=0;r<m;r++){vector<int>z;for(int k=0;k<m;k++)z.push_back(q[(r+k)%m]);if(z<best)best=z;}}return best;}
struct Search{
 Case C;int B,EP,d,y,base,nmax;vector<int>cap;vector<U>baseg,g;vector<vector<vector<POpt>>> P;vector<COpt> Cyc;long long localNodes=0,edgeChecks=0,globalStates=0,cycleStates=0;vector<POpt> solP;vector<COpt> solC;
 Search(Case cc):C(cc){B=C.B;EP=C.ed.size();d=2*B-EP;y=2*d+C.E;base=B+EP;nmax=base+y;cap.assign(B,0);vector<int>deg(B);for(auto [u,v]:C.ed)deg[u]++,deg[v]++;for(int v=0;v<B;v++)cap[v]=4+((C.E&&v==C.sp)?1:0)-deg[v];baseg.assign(nmax,0);for(int e=0;e<EP;e++){add(baseg,B+e,C.ed[e].first);add(baseg,B+e,C.ed[e].second);}g=baseg;P.resize(EP,vector<vector<POpt>>(EP));}
 void genPaths(){vector<int>rem=cap;vector<uint8_t>w;array<uint8_t,8>cnt{};long long dummy=0;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){
   // r=0
   auto h0=baseg; if(safe_add(h0,B+i,B+j,dummy)){POpt o;o.i=i;o.j=j;P[i][j].push_back(o);} 
   function<void(int,vector<U>&)> rec=[&](int dep,vector<U>&h){localNodes++;if(dep>=y)return;int prev=dep?base+dep-1:B+i,node=base+dep;for(int lab=0;lab<B;lab++)if(rem[lab]){vector<pair<int,int>>added;add(h,node,lab);added.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=safe_add(h,prev,node,dummy);if(ok)added.push_back({prev,node});if(ok){bool closed=safe_add(h,node,B+j,dummy);if(closed){POpt o;o.i=i;o.j=j;o.w=w;o.cnt=cnt;P[i][j].push_back(o);del(h,node,B+j);}rec(dep+1,h);}for(auto it=added.rbegin();it!=added.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};
   auto h=baseg;rec(0,h);
 }
 }
 void genCycles(){vector<int>rem=cap;vector<uint8_t>w;array<uint8_t,8>cnt{};long long dummy=0;set<vector<int>>seenCanon;for(int m=3;m<=y;m++){function<void(int,vector<U>&)>rec=[&](int pos,vector<U>&h){localNodes++;if(pos==m){bool ok=safe_add(h,base+m-1,base,dummy);if(ok){auto can=canon_cycle(w);if(seenCanon.insert(can).second){COpt o;o.w=w;o.cnt=cnt;Cyc.push_back(o);}del(h,base+m-1,base);}return;}for(int lab=0;lab<B;lab++)if(rem[lab]){if(pos>0&&lab<w[0])continue;int node=base+pos;vector<pair<int,int>>added;add(h,node,lab);added.push_back({node,lab});rem[lab]--;cnt[lab]++;w.push_back(lab);bool ok=true;if(pos>0){ok=safe_add(h,base+pos-1,node,dummy);if(ok)added.push_back({base+pos-1,node});}if(ok)rec(pos+1,h);for(auto it=added.rbegin();it!=added.rend();++it)del(h,it->first,it->second);w.pop_back();cnt[lab]--;rem[lab]++;}};auto h=baseg;rec(0,h);} }
 bool fits(const array<uint8_t,8>&cnt,const array<int,8>&rem){for(int v=0;v<B;v++)if(cnt[v]>rem[v])return false;return true;}
 bool addPathGlobal(const POpt&o,int usedY,vector<pair<int,int>>&added){if(o.w.empty()){if(!safe_add(g,B+o.i,B+o.j,edgeChecks))return false;added.push_back({B+o.i,B+o.j});return true;}int prev=B+o.i;for(int k=0;k<(int)o.w.size();k++){int node=base+usedY+k,lab=o.w[k];add(g,node,lab);added.push_back({node,lab});if(!safe_add(g,prev,node,edgeChecks))return false;added.push_back({prev,node});prev=node;}if(!safe_add(g,prev,B+o.j,edgeChecks))return false;added.push_back({prev,B+o.j});return true;}
 bool addCycleGlobal(const COpt&o,int usedY,vector<pair<int,int>>&added){int m=o.w.size();for(int k=0;k<m;k++){int node=base+usedY+k,lab=o.w[k];add(g,node,lab);added.push_back({node,lab});if(k>0){if(!safe_add(g,base+usedY+k-1,node,edgeChecks))return false;added.push_back({base+usedY+k-1,node});}}if(!safe_add(g,base+usedY+m-1,base+usedY,edgeChecks))return false;added.push_back({base+usedY+m-1,base+usedY});return true;}
 void undo(vector<pair<int,int>>&added){for(auto it=added.rbegin();it!=added.rend();++it)del(g,it->first,it->second);}
 bool fillCycles(array<int,8>&rem,int usedY,vector<int>&dummy){cycleStates++;int total=0;for(int v=0;v<B;v++)total+=rem[v];if(total==0)return true;int v0=0;while(v0<B&&rem[v0]==0)v0++;for(auto&o:Cyc){if(o.cnt[v0]==0||!fits(o.cnt,rem))continue;vector<pair<int,int>>added;if(!addCycleGlobal(o,usedY,added)){undo(added);continue;}for(int v=0;v<B;v++)rem[v]-=o.cnt[v];solC.push_back(o);if(fillCycles(rem,usedY+o.w.size(),dummy))return true;solC.pop_back();for(int v=0;v<B;v++)rem[v]+=o.cnt[v];undo(added);}return false;}
 bool dfsPaths(uint16_t mask,array<int,8>&rem,int usedY){globalStates++;if(mask==(1u<<EP)-1){vector<int>lc;return fillCycles(rem,usedY,lc);}int i=0;while(mask>>i&1)i++;for(int j=i+1;j<EP;j++)if(!(mask>>j&1)){for(auto&o:P[i][j]){if(!fits(o.cnt,rem))continue;vector<pair<int,int>>added;if(!addPathGlobal(o,usedY,added)){undo(added);continue;}for(int v=0;v<B;v++)rem[v]-=o.cnt[v];solP.push_back(o);if(dfsPaths(mask|(1u<<i)|(1u<<j),rem,usedY+o.w.size()))return true;solP.pop_back();for(int v=0;v<B;v++)rem[v]+=o.cnt[v];undo(added);}}return false;}
 bool run(){genPaths();genCycles();array<int,8>rem{};for(int v=0;v<B;v++)rem[v]=cap[v];return dfsPaths(0,rem,0);} 
 void report(bool yes){long long pc=0;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++)pc+=P[i][j].size();cout<<(yes?"GLOBAL_SAT":"GLOBAL_UNSAT")<<" idx="<<C.idx<<" "<<C.core<<" E="<<C.E<<" sp="<<C.sp<<" pathWords="<<pc<<" cycleWords="<<Cyc.size()<<" states="<<globalStates<<" cstates="<<cycleStates<<" edgeChecks="<<edgeChecks<<" localNodes="<<localNodes<<"\n";if(yes){for(auto&o:solP){cout<<" PATH "<<o.i<<" "<<o.j<<" W";for(auto x:o.w)cout<<" "<<(int)x;cout<<"\n";}for(auto&o:solC){cout<<" CYCLE W";for(auto x:o.w)cout<<" "<<(int)x;cout<<"\n";}}
 }
};
int main(int argc,char**argv){if(argc<2){cerr<<"usage cases [lo hi]\n";return 2;}auto cs=readcases(argv[1]);int lo=0,hi=cs.size();if(argc>=4){lo=stoi(argv[2]);hi=stoi(argv[3]);}for(int i=lo;i<hi;i++){Search s(cs[i]);bool y=s.run();s.report(y);} }
