#include <bits/stdc++.h>
using namespace std; using U=uint64_t;
struct Case{int B,E,sp,idx;string core;vector<pair<int,int>>ed;};
struct Cert{int idx,B,E,sp,muT,lamSum;string core;vector<int>mu,lam;};
using Key=tuple<int,int,string,int>;
static Key key(const Case&c){return {c.B,c.E,c.core,c.sp};} static Key key(const Cert&c){return {c.B,c.E,c.core,c.sp};}
static void add(vector<U>&a,int u,int v){a[u]|=1ULL<<v;a[v]|=1ULL<<u;} static void del(vector<U>&a,int u,int v){a[u]&=~(1ULL<<v);a[v]&=~(1ULL<<u);}
static bool cycdfs(const vector<U>&a,int s,int v,int L,int dep,U used,int first){if(dep==L-1)return ((a[v]>>s)&1ULL)&&first<v;U c=a[v]&~used;while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);if(cycdfs(a,s,w,L,dep+1,used|b,first))return true;}return false;}
static bool cycle_through(const vector<U>&a,int s,int L){U c=a[s];while(c){U b=c&-c;c-=b;int f=__builtin_ctzll(b);if(cycdfs(a,s,f,L,1,(1ULL<<s)|b,f))return true;}return false;}
static bool forbidden_through(const vector<U>&a,int s){return cycle_through(a,s,4)||cycle_through(a,s,8)||cycle_through(a,s,16);} 
static bool has_cycle_len(const vector<U>&a,int L){for(int s=0;s<(int)a.size();s++)if(cycle_through(a,s,L))return true;return false;}
static bool two_deg(int n,const vector<pair<int,int>>&ed){vector<U>a(n);for(auto [u,v]:ed)add(a,u,v);U alive=(1ULL<<n)-1;vector<int>d(n);for(int i=0;i<n;i++)d[i]=__builtin_popcountll(a[i]);for(int k=0;k<n;k++){int v=-1;for(int i=0;i<n;i++)if((alive>>i&1ULL)&&d[i]<=2){v=i;break;}if(v<0)return false;alive&=~(1ULL<<v);U c=a[v]&alive;while(c){U b=c&-c;c-=b;--d[__builtin_ctzll(b)];}}return true;}
static vector<Case> readcases(const string&p){ifstream in(p);string l;if(!getline(in,l)||l!="ENDPOINT_CASES_V1")throw runtime_error("case header");vector<Case>o;int idx=0;while(getline(in,l)){if(l=="END")break;if(l.empty())continue;istringstream ss(l);string t;Case c;ss>>t>>c.B>>c.E>>c.core>>c.sp;if(t!="CASE")throw runtime_error("CASE");getline(in,l);istringstream es(l);es>>t;string x;while(es>>x){auto z=x.find(',');c.ed.push_back({stoi(x.substr(0,z)),stoi(x.substr(z+1))});}getline(in,l);c.idx=idx++;o.push_back(c);}return o;}
static vector<string> csvsplit(const string&s){vector<string>v;string x;bool q=false;for(char ch:s){if(ch=='\"'){q=!q;continue;}if(ch==','&&!q){v.push_back(x);x.clear();}else x+=ch;}v.push_back(x);return v;}
static vector<int> ints(const string&s){istringstream ss(s);vector<int>v;int x;while(ss>>x)v.push_back(x);return v;}
static vector<Cert> readcert(const string&p){ifstream in(p);string l;if(!getline(in,l))throw runtime_error("cert header");vector<Cert>o;while(getline(in,l)){if(l.empty())continue;auto f=csvsplit(l);if(f.size()!=9)throw runtime_error("cert fields");Cert c;c.idx=stoi(f[0]);c.B=stoi(f[1]);c.E=stoi(f[2]);c.core=f[3];c.sp=stoi(f[4]);c.muT=stoi(f[5]);c.lamSum=stoi(f[6]);c.mu=ints(f[7]);c.lam=ints(f[8]);o.push_back(c);}return o;}
int main(int argc,char**argv){if(argc<3){cerr<<"usage: checker cases cert\n";return 2;}auto cs=readcases(argv[1]);auto cert=readcert(argv[2]);map<Key,Cert> CM;map<Key,int> mult;for(auto&c:cert){CM[key(c)]=c;mult[key(c)]++;}int miss=0,extra=0,dup=0;set<Key> CK;for(auto&c:cs)CK.insert(key(c));for(auto&c:cs)if(!CM.count(key(c)))miss++;for(auto&c:cert)if(!CK.count(key(c)))extra++;for(auto&[k,n]:mult)if(n!=1)dup++;cout<<"PARTITION cases="<<cs.size()<<" cert="<<cert.size()<<" missing="<<miss<<" extra="<<extra<<" dup="<<dup<<"\n";if(miss||extra||dup)return 3;
 long long states=0,attempts=0,closures=0;map<int,int> secn;int checked=0;
 for(auto&C:cs){auto Z=CM[key(C)];int B=C.B,EP=C.ed.size(),d=2*B-EP,y=2*d+C.E,base=B+EP;if(B!=8||d!=6){cerr<<"bad d case "<<C.idx<<"\n";return 4;}if((int)Z.mu.size()!=B||(int)Z.lam.size()!=EP){cerr<<"length fail "<<C.idx<<"\n";return 5;}for(int x:Z.mu)if(x<0||x>2){cerr<<"mu range\n";return 6;}for(int x:Z.lam)if(x<0||x>2){cerr<<"lam range\n";return 6;}
  vector<int>deg(B);set<pair<int,int>>seen;for(auto [u0,v0]:C.ed){int u=u0,v=v0;if(u>v)swap(u,v);if(u==v||!seen.insert({u,v}).second){cerr<<"Q simple fail\n";return 7;}deg[u]++,deg[v]++;}if(!two_deg(B,C.ed)){cerr<<"Q 2deg fail\n";return 8;}vector<U>q(B);for(auto e:C.ed)add(q,e.first,e.second);if(has_cycle_len(q,4)||has_cycle_len(q,8)){cerr<<"Q cycle fail\n";return 9;}
  vector<int>cap(B);for(int v=0;v<B;v++){cap[v]=4+((C.E&&v==C.sp)?1:0)-deg[v];if(cap[v]<0){cerr<<"cap neg\n";return 10;}}if(accumulate(cap.begin(),cap.end(),0)!=y){cerr<<"cap sum\n";return 11;}int muT=0;for(int v=0;v<B;v++)muT+=Z.mu[v]*cap[v];int lamS=accumulate(Z.lam.begin(),Z.lam.end(),0);if(muT!=Z.muT||lamS!=Z.lamSum||muT<=lamS){cerr<<"global charge fail idx="<<C.idx<<" calc="<<muT<<","<<lamS<<" cert="<<Z.muT<<","<<Z.lamSum<<"\n";return 12;}
  int nmax=base+y;vector<U>g(nmax);for(int e=0;e<EP;e++){add(g,B+e,C.ed[e].first);add(g,B+e,C.ed[e].second);} // base skeleton no C4/8/16 follows from Q simple,C4,C8; checked above
  vector<int>rem=cap;int wsum=0;
  for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){int st=B+i,tg=B+j,lim=Z.lam[i]+Z.lam[j];function<bool(int)>rec=[&](int dep){states++;if(dep>=y)return true;int prev=dep?base+dep-1:st,node=base+dep;for(int lab=0;lab<B;lab++)if(rem[lab]){attempts++;add(g,node,lab);add(g,prev,node);rem[lab]--;wsum+=Z.mu[lab];bool bad=forbidden_through(g,node);if(!bad){if(wsum>lim){add(g,node,tg);closures++;bool cbad=forbidden_through(g,node);del(g,node,tg);if(!cbad){cerr<<"CHARGE VIOLATION idx="<<C.idx<<" pair="<<i<<","<<j<<" weight="<<wsum<<" lim="<<lim<<" depth="<<(dep+1)<<"\n";return false;}}if(!rec(dep+1))return false;}wsum-=Z.mu[lab];rem[lab]++;del(g,prev,node);del(g,node,lab);}return true;};if(!rec(0))return 20;}
  checked++;secn[C.E]++;
 }
 cout<<"PASS checked="<<checked<<" states="<<states<<" attempts="<<attempts<<" closures="<<closures<<"\n";for(auto&[E,n]:secn)cout<<"SECTOR 8,"<<E<<" cases="<<n<<"\n";
}
