#include <bits/stdc++.h>
using namespace std;using U=uint64_t;const int B=14,EP=20,MAXN=40;
struct G{U a[MAXN]{};int n=0;void add(int u,int v){a[u]|=1ULL<<v;a[v]|=1ULL<<u;}void del(int u,int v){a[u]&=~(1ULL<<v);a[v]&=~(1ULL<<u);}bool path(int s,int t,int L){function<bool(int,int,U)>f=[&](int v,int d,U used)->bool{if(d==L)return v==t;U c=a[v]&~used;if(d<L-1)c&=~(1ULL<<t);while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);if(f(w,d+1,used|b))return true;}return false;};return f(s,0,1ULL<<s);}bool safe(int u,int v){return !((a[u]>>v)&1ULL)&&!path(u,v,3)&&!path(u,v,7)&&!path(u,v,15);}};
struct Opt{int i,j,k,p,q;bool operator==(Opt const&o)const{return tie(i,j,k,p,q)==tie(o.i,o.j,o.k,o.p,o.q);}};struct BR{int oi,ch;};struct ST{U m;int p;vector<int>r;vector<BR>b;};
bool trig(pair<int,int>e,pair<int,int>f,int k,int p,int q,int sp){int c[14]{};c[e.first]++;c[e.second]++;c[f.first]++;c[f.second]++;if(k>=1)c[p]++;if(k>=2)c[q]++;for(int v=0;v<14;v++){int need=v==sp?3:2;if(c[v]>=need)return true;}return false;}
bool local(G&g,int i,int j,int k,int p,int q){int old=g.n;vector<pair<int,int>>ad;vector<int>vs{B+i};if(k>=1){int x=g.n++;g.add(x,p);ad.push_back({x,p});vs.push_back(x);}if(k>=2){int x=g.n++;g.add(x,q);ad.push_back({x,q});vs.push_back(x);}vs.push_back(B+j);for(int r=0;r+1<(int)vs.size();r++){int u=vs[r],v=vs[r+1];if(!g.safe(u,v)){for(auto it=ad.rbegin();it!=ad.rend();++it)g.del(it->first,it->second);g.n=old;return false;}g.add(u,v);ad.push_back({u,v});}for(auto it=ad.rbegin();it!=ad.rend();++it)g.del(it->first,it->second);g.n=old;return true;}
bool exactQ(const vector<vector<int>>&a,int s,int t,int L){vector<int>used(14);function<bool(int,int)>f=[&](int v,int d){if(d==L)return v==t;for(int w:a[v])if(!used[w]&&!(w==t&&d<L-1)){used[w]=1;if(f(w,d+1))return true;used[w]=0;}return false;};used[s]=1;return f(s,0);}
int main(int argc,char**argv){if(argc!=2)return 2;ifstream in(argv[1]);string t,k;int lo,hi;in>>t>>k>>lo>>hi;if(t!="CERT_V1"||k!="B14E1_EMPTY_CHUNK"||lo<0||hi<lo)return 3;long long no=0,ns=0,nb=0;for(int ci=lo;ci<hi;ci++){int id,qi,sp,nopt,nst,root;vector<int>cap(14);in>>t>>id>>qi>>sp>>nopt>>nst>>root;if(t!="CASE"||id!=ci)return 4;for(int&x:cap)in>>x;in>>t;if(t!="EDGES")return 5;vector<pair<int,int>>ed;for(int z=0;z<EP;z++){string s;in>>s;auto p=s.find(',');ed.push_back({stoi(s.substr(0,p)),stoi(s.substr(p+1))});}vector<Opt>co(nopt);for(int oi=0;oi<nopt;oi++){int x;in>>t>>x>>co[oi].i>>co[oi].j>>co[oi].k>>co[oi].p>>co[oi].q;if(t!="OPT"||x!=oi)return 6;}vector<ST>st(nst);for(int si=0;si<nst;si++){int x,n;in>>t>>x>>st[si].m>>st[si].p>>n;if(t!="STATE"||x!=si)return 7;st[si].r.resize(14);for(int&v:st[si].r)in>>v;for(int z=0;z<n;z++){BR b;in>>t>>b.oi>>b.ch;if(t!="BR")return 8;st[si].b.push_back(b);}}in>>t;if(t!="ENDCASE")return 9;
 int deg[14]{};vector<vector<int>>qa(14);G g;g.n=B+EP;for(int z=0;z<EP;z++){auto[u,v]=ed[z];deg[u]++;deg[v]++;qa[u].push_back(v);qa[v].push_back(u);int a=B+z;g.add(a,u);g.add(a,v);}vector<int>ec(14),labs;for(int v=0;v<14;v++){ec[v]=4+(v==sp)-deg[v];if(ec[v]<0)return 10;if(ec[v])labs.push_back(v);}if(ec!=cap)return 11;
 // Verify D_Q is empty, hence any path with >=3 internal vertices would have a distance-2 forbidden pair.
 for(int ii=0;ii<(int)labs.size();ii++)for(int jj=ii+1;jj<(int)labs.size();jj++){int p=labs[ii],q=labs[jj];if(!exactQ(qa,p,q,2)&&!exactQ(qa,p,q,6)){cerr<<"nonempty D_Q case "<<ci<<"\n";return 12;}}
 vector<Opt>ro;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){if(trig(ed[i],ed[j],0,-1,-1,sp)&&local(g,i,j,0,-1,-1))ro.push_back({i,j,0,-1,-1});for(int p:labs)if(trig(ed[i],ed[j],1,p,-1,sp)&&local(g,i,j,1,p,-1))ro.push_back({i,j,1,p,-1});for(int p:labs)for(int q:labs){if(p==q&&cap[p]<2)continue;if(trig(ed[i],ed[j],2,p,q,sp)&&local(g,i,j,2,p,q))ro.push_back({i,j,2,p,q});}}
 if(ro!=co){cerr<<"option mismatch "<<ci<<"\n";return 13;}vector<vector<int>>by(EP);for(int oi=0;oi<nopt;oi++){by[co[oi].i].push_back(oi);by[co[oi].j].push_back(oi);}for(int si=0;si<nst;si++){auto&S=st[si];if(S.m==(1ULL<<EP)-1){bool z=true;for(int x:S.r)if(x)z=false;if(z||S.p!=-1||!S.b.empty())return 14;continue;}int best=-1;vector<int>cb;for(int v=0;v<EP;v++)if(!((S.m>>v)&1ULL)){vector<int>c;for(int oi:by[v]){auto&o=co[oi];int w=o.i==v?o.j:o.i;if((S.m>>w)&1ULL)continue;bool ok=true;if(o.k>=1&&S.r[o.p]<1)ok=false;if(o.k>=2){if(o.p==o.q){if(S.r[o.p]<2)ok=false;}else if(S.r[o.q]<1)ok=false;}if(ok)c.push_back(oi);}if(c.empty()){best=v;cb.clear();break;}if(best<0||c.size()<cb.size()){best=v;cb=c;}}if(S.p!=best||S.b.size()!=cb.size())return 15;for(size_t z=0;z<cb.size();z++){if(S.b[z].oi!=cb[z])return 16;auto&o=co[cb[z]];auto nr=S.r;if(o.k>=1)nr[o.p]--;if(o.k>=2)nr[o.q]--;U nm=S.m|(1ULL<<o.i)|(1ULL<<o.j);int left=(EP-__builtin_popcountll(nm))/2,total=0;for(int x:nr)total+=x;int ch=S.b[z].ch;if(total>2*left){if(ch!=-1)return 17;}else if(ch<0||ch>=si||st[ch].m!=nm||st[ch].r!=nr)return 18;}}if(root<0||root>=nst||st[root].m!=0||st[root].r!=cap)return 19;no+=nopt;ns+=nst;for(auto&S:st)nb+=S.b.size();}
in>>t;if(t!="ENDCERT")return 20;cout<<"PASS RANGE "<<lo<<" "<<hi<<" OPTIONS "<<no<<" STATES "<<ns<<" BRANCHES "<<nb<<"\n";}
