#include <bits/stdc++.h>
using namespace std;using U=uint64_t;const int B=14,EP=20,MAXN=48;
struct G{U a[MAXN]{};int n=0;void add(int u,int v){a[u]|=1ULL<<v;a[v]|=1ULL<<u;}void del(int u,int v){a[u]&=~(1ULL<<v);a[v]&=~(1ULL<<u);}bool path(int s,int t,int L){function<bool(int,int,U)>f=[&](int v,int d,U used)->bool{if(d==L)return v==t;U c=a[v]&~used;if(d<L-1)c&=~(1ULL<<t);while(c){U b=c&-c;c-=b;int w=__builtin_ctzll(b);if(f(w,d+1,used|b))return true;}return false;};return f(s,0,1ULL<<s);}bool safe(int u,int v){return !((a[u]>>v)&1ULL)&&!path(u,v,3)&&!path(u,v,7)&&!path(u,v,15);}};
struct Opt{int i,j;vector<int>s;bool operator==(Opt const&o)const{return i==o.i&&j==o.j&&s==o.s;}};struct BR{int oi,ch;};struct ST{U m;int p;vector<int>r;vector<BR>b;};
bool trig(pair<int,int>e,pair<int,int>f,const vector<int>&s,int sp){int c[14]{};c[e.first]++;c[e.second]++;c[f.first]++;c[f.second]++;for(int x:s)c[x]++;for(int v=0;v<14;v++){int need=v==sp?3:2;if(c[v]>=need)return true;}return false;}
int maxword(const vector<pair<int,int>>&ed,const vector<int>&cap,int &dEdges){vector<vector<int>>a(14);for(auto[u,v]:ed){a[u].push_back(v);a[v].push_back(u);}auto pe=[&](int s,int t,int L){vector<int>used(14);function<bool(int,int)>f=[&](int v,int d){if(d==L)return v==t;for(int w:a[v])if(!used[w]&&!(w==t&&d<L-1)){used[w]=1;if(f(w,d+1))return true;used[w]=0;}return false;};used[s]=1;return f(s,0);};bool D[14][14]{};vector<int>U;for(int v=0;v<14;v++)if(cap[v])U.push_back(v);dEdges=0;for(int p:U)for(int q:U)if(p<q&&!pe(p,q,2)&&!pe(p,q,6)){D[p][q]=D[q][p]=1;dEdges++;}int best=0;vector<int>rem=cap,s;function<void()>dfs=[&](){best=max(best,(int)s.size());for(int v:U)if(rem[v]){if(s.size()>=2&&!D[s[s.size()-2]][v])continue;rem[v]--;s.push_back(v);dfs();s.pop_back();rem[v]++;}};dfs();return best;}
vector<Opt>regen(const vector<pair<int,int>>&ed,const vector<int>&cap,int K,int sp){G g;g.n=B+EP;for(int i=0;i<EP;i++){auto[u,v]=ed[i];int a=B+i;g.add(a,u);g.add(a,v);}vector<Opt>out;for(int i=0;i<EP;i++)for(int j=i+1;j<EP;j++){vector<int>s;vector<int>rem=cap;if(trig(ed[i],ed[j],s,sp)){int u=B+i,v=B+j;if(g.safe(u,v))out.push_back({i,j,s});}function<void(int)>dfs=[&](int last){if((int)s.size()>=K)return;for(int lab=0;lab<14;lab++)if(rem[lab]){int x=g.n++;g.add(x,lab);if(g.safe(last,x)){g.add(last,x);s.push_back(lab);rem[lab]--;if(trig(ed[i],ed[j],s,sp)){int v=B+j;if(g.safe(x,v))out.push_back({i,j,s});}dfs(x);rem[lab]++;s.pop_back();g.del(last,x);}g.del(x,lab);g.n--;}};dfs(B+i);}return out;}
int main(int argc,char**argv){if(argc!=2)return 2;ifstream in(argv[1]);string t,k;int lo,hi;in>>t>>k>>lo>>hi;if(t!="CERT_V1"||k!="B14E1_BAD_CHUNK")return 3;long long NO=0,NS=0,NB=0;int maxK=0;for(int ci=lo;ci<hi;ci++){int id,qi,sp,nopt,nst,root;vector<int>cap(14);in>>t>>id>>qi>>sp>>nopt>>nst>>root;if(t!="CASE"||id!=ci)return 4;for(int&x:cap)in>>x;in>>t;if(t!="EDGES")return 5;vector<pair<int,int>>ed;for(int z=0;z<EP;z++){string s;in>>s;auto p=s.find(',');ed.push_back({stoi(s.substr(0,p)),stoi(s.substr(p+1))});}vector<Opt>co(nopt);for(int oi=0;oi<nopt;oi++){int x,l;in>>t>>x>>co[oi].i>>co[oi].j>>l;if(t!="OPT"||x!=oi)return 6;co[oi].s.resize(l);for(int&v:co[oi].s)in>>v;}vector<ST>st(nst);for(int si=0;si<nst;si++){int x,n;in>>t>>x>>st[si].m>>st[si].p>>n;if(t!="STATE"||x!=si)return 7;st[si].r.resize(14);for(int&v:st[si].r)in>>v;for(int z=0;z<n;z++){BR b;in>>t>>b.oi>>b.ch;if(t!="BR")return 8;st[si].b.push_back(b);}}in>>t;if(t!="ENDCASE")return 9;
 int deg[14]{};for(auto[u,v]:ed){deg[u]++;deg[v]++;}vector<int>ec(14);for(int v=0;v<14;v++){ec[v]=4+(v==sp)-deg[v];if(ec[v]<0)return 10;}if(ec!=cap)return 11;int de=0,K=maxword(ed,cap,de);if(de==0||K>8){cerr<<"bad D/maxword case "<<ci<<" D="<<de<<" K="<<K<<"\n";return 12;}maxK=max(maxK,K);auto ro=regen(ed,cap,K,sp);if(ro!=co){cerr<<"option mismatch case "<<ci<<" K="<<K<<" regen="<<ro.size()<<" cert="<<co.size()<<"\n";return 13;}
 vector<vector<int>>by(EP);for(int oi=0;oi<nopt;oi++){by[co[oi].i].push_back(oi);by[co[oi].j].push_back(oi);}for(int si=0;si<nst;si++){auto&S=st[si];if(S.m==(1ULL<<EP)-1){bool z=true;for(int x:S.r)if(x)z=false;if(z||S.p!=-1||!S.b.empty())return 14;continue;}int best=-1;vector<int>cb;for(int v=0;v<EP;v++)if(!((S.m>>v)&1ULL)){vector<int>c;for(int oi:by[v]){auto&o=co[oi];int w=o.i==v?o.j:o.i;if((S.m>>w)&1ULL)continue;auto rr=S.r;bool ok=true;for(int x:o.s)if(--rr[x]<0){ok=false;break;}if(ok)c.push_back(oi);}if(c.empty()){best=v;cb.clear();break;}if(best<0||c.size()<cb.size()){best=v;cb=c;}}if(S.p!=best||S.b.size()!=cb.size())return 15;for(size_t z=0;z<cb.size();z++){if(S.b[z].oi!=cb[z])return 16;auto&o=co[cb[z]];auto nr=S.r;for(int x:o.s)nr[x]--;U nm=S.m|(1ULL<<o.i)|(1ULL<<o.j);int left=(EP-__builtin_popcountll(nm))/2,total=0;for(int x:nr)total+=x;int ch=S.b[z].ch;if(total>8*left){if(ch!=-1)return 17;}else if(ch<0||ch>=si||st[ch].m!=nm||st[ch].r!=nr)return 18;}}if(root<0||root>=nst||st[root].m!=0||st[root].r!=cap)return 19;NO+=nopt;NS+=nst;for(auto&S:st)NB+=S.b.size();}
in>>t;if(t!="ENDCERT")return 20;cout<<"PASS RANGE "<<lo<<" "<<hi<<" OPTIONS "<<NO<<" STATES "<<NS<<" BRANCHES "<<NB<<" MAXK "<<maxK<<"\n";}
